[package]
name = "idolmap"
version = "0.2.0"
authors = ["Kohei Suzuki <eagletmt@gmail.com>"]

[dependencies]
clap = "2.31"
csv = "1.0.0-beta.5"
env_logger = "0.5"
reqwest = "0.8"
kuchiki = "0.7"
log = "0.4"
selectors = "0.19"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.7"
